# Generated by Django 5.2.7 on 2025-10-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text='Введите вашу фамилию', max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(help_text='Введите ваше имя', max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, help_text='your.email@example.com', max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='+7 (XXX) XXX-XX-XX', max_length=20, null=True, verbose_name='Телефон')),
                ('school', models.CharField(blank=True, help_text='Название учебного заведения', max_length=200, null=True, verbose_name='Учебное заведение')),
                ('education_level', models.CharField(blank=True, choices=[('school', 'Среднее образование'), ('college', 'Среднее специальное'), ('bachelor', 'Бакалавриат'), ('master', 'Магистратура'), ('phd', 'Аспирантура')], max_length=20, null=True, verbose_name='Уровень образования')),
                ('specialization', models.CharField(blank=True, help_text='Ваша специальность или направление', max_length=200, null=True, verbose_name='Специализация')),
                ('experience', models.TextField(blank=True, help_text='Опишите ваш опыт работы, стажировки, проекты...', null=True, verbose_name='Опыт работы')),
                ('hobbies', models.TextField(blank=True, help_text='Опишите ваши хобби и интересы...', null=True, verbose_name='Увлечения')),
                ('skills', models.TextField(blank=True, help_text='Список ваших навыков', null=True, verbose_name='Навыки')),
                ('achievements', models.TextField(blank=True, help_text='Расскажите о ваших наградах, проектах, сертификатах...', null=True, verbose_name='Достижения')),
                ('goals', models.TextField(blank=True, help_text='Кем вы хотите стать? Каких целей планируете достичь?', null=True, verbose_name='Карьерные цели')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
                'ordering': ['-created_at'],
            },
        ),
    ]
